// GENERATED by scripts/gen-quiz-images.mjs — do not edit by hand.
// Rerun with `npm run gen:quiz-images` (also runs before dev and build).

export const AVAILABLE_QUIZ_IMAGES: ReadonlySet<string> = new Set([
  "/quiz/false-starts.png",
  "/quiz/goal-build.png",
  "/quiz/injury.png",
  "/quiz/level-advanced.png",
  "/quiz/level-beginner.png",
  "/quiz/level-consistent.png",
  "/quiz/level-returning.png",
  "/quiz/motivation.jpg",
  "/quiz/no-plan.png",
  "/quiz/no-time.png",
  "/quiz/vision-confident.png",
  "/quiz/vision-energised.png",
  "/quiz/vision-proud.png",
]);
