// GENERATED by scripts/gen-quiz-images.mjs — do not edit by hand.
// Rerun with `npm run gen:quiz-images` (also runs before dev and build).

export const AVAILABLE_QUIZ_IMAGES: ReadonlySet<string> = new Set([

]);
